version: '3.9'

volumes:
   geoserver-data:

services:
   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      volumes:
        - /etc/certs:/etc/certs
      restart: on-failure
      environment:
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=SS1974GL
        - GEOSERVER_ADMIN_USER=admin_speri
        - HTTP_PROXY_NAME=geo.mana-surf.com
        - HTTP_SCHEME=https
        # - CATALINA_OPTS=-DHTTP_PROXY_NAME=${HTTP_PROXY_NAME}
      healthcheck:
        test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:'${GEOSERVER_ADMIN_PASSWORD}' http://localhost:8080/geoserver/rest/about/version.xml"
        interval: 1m30s
        timeout: 10s
        retries: 3
      ports:
       - "8443:8443"
       - "8600:8080"

   nginx:
     image: nginx
     volumes:
       - /etc/letsencrypt:/etc/letsencrypt
       - ./sites-enabled:/etc/nginx/conf.d:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     depends_on:
       - geoserver
     ports:
       - "443:443"
       - "80:80"
     restart: always
